// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"regexp"
	"time"

	"github.com/kilianpaquier/gitlab-storage-cleaner/internal/artifacts/v2"
)

// OptionsBuilder is an alias of Options to build Options with builder-pattern.
type OptionsBuilder artifacts.Options

// NewOptionsBuilder creates a new OptionsBuilder.
func NewOptionsBuilder() *OptionsBuilder {
	return &OptionsBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *OptionsBuilder) Copy() *OptionsBuilder {
	c := *b
	return &c
}

// Build returns built Options.
func (b *OptionsBuilder) Build() *artifacts.Options {
	c := (artifacts.Options)(*b)
	return &c
}

// SetDryRun sets Options's DryRun.
func (b *OptionsBuilder) SetDryRun(dryRun bool) *OptionsBuilder {
	b.DryRun = dryRun
	return b
}

// SetPathRegexps sets Options's PathRegexps.
func (b *OptionsBuilder) SetPathRegexps(pathRegexps ...*regexp.Regexp) *OptionsBuilder {
	b.PathRegexps = append(b.PathRegexps, pathRegexps...)
	return b
}

// SetPaths sets Options's Paths.
func (b *OptionsBuilder) SetPaths(paths ...string) *OptionsBuilder {
	b.Paths = append(b.Paths, paths...)
	return b
}

// SetThresholdDuration sets Options's ThresholdDuration.
func (b *OptionsBuilder) SetThresholdDuration(thresholdDuration time.Duration) *OptionsBuilder {
	b.ThresholdDuration = thresholdDuration
	return b
}

// SetThresholdSize sets Options's ThresholdSize.
func (b *OptionsBuilder) SetThresholdSize(thresholdSize uint64) *OptionsBuilder {
	b.ThresholdSize = thresholdSize
	return b
}

// SetThresholdTime sets Options's ThresholdTime.
func (b *OptionsBuilder) SetThresholdTime(thresholdTime time.Time) *OptionsBuilder {
	b.ThresholdTime = thresholdTime
	return b
}
