// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package tests

import (
	"github.com/kilianpaquier/gitlab-storage-cleaner/internal/artifacts/v2"
)

// ProjectBuilder is an alias of Project to build Project with builder-pattern.
type ProjectBuilder artifacts.Project

// NewProjectBuilder creates a new ProjectBuilder.
func NewProjectBuilder() *ProjectBuilder {
	return &ProjectBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *ProjectBuilder) Copy() *ProjectBuilder {
	c := *b
	return &c
}

// Build returns built Project.
func (b *ProjectBuilder) Build() *artifacts.Project {
	c := (artifacts.Project)(*b)
	return &c
}

// SetID sets Project's ID.
func (b *ProjectBuilder) SetID(id int) *ProjectBuilder {
	b.ID = id
	return b
}

// SetJobsCleaned sets Project's JobsCleaned.
func (b *ProjectBuilder) SetJobsCleaned(jobsCleaned int) *ProjectBuilder {
	b.JobsCleaned = jobsCleaned
	return b
}

// SetPathWithNamespace sets Project's PathWithNamespace.
func (b *ProjectBuilder) SetPathWithNamespace(pathWithNamespace string) *ProjectBuilder {
	b.PathWithNamespace = pathWithNamespace
	return b
}
