# Code generated by craft; DO NOT EDIT.

#############################
#        STAGE BUILD        #
#############################
FROM python:3

WORKDIR /app

#############################
#         STAGE RUN         #
#############################
FROM gcr.io/distroless/static-debian12:nonroot

LABEL org.opencontainers.image.authors="kilianpaquier"
LABEL org.opencontainers.image.vendor="kilianpaquier"

LABEL org.opencontainers.image.title="gitlab-storage-cleaner"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.url="github.com/kilianpaquier/gitlab-storage-cleaner"
LABEL org.opencontainers.image.source="github.com/kilianpaquier/gitlab-storage-cleaner"
LABEL org.opencontainers.image.documentation="github.com/kilianpaquier/gitlab-storage-cleaner"

WORKDIR /app
