# Code generated by craft; DO NOT EDIT.

#############################
#        STAGE BUILD        #
#############################
FROM golang:1.23.3 AS build

WORKDIR /app

COPY . .

# hadolint ignore=DL3059
RUN go mod download
# hadolint ignore=DL3059
RUN CGO_ENABLED=0 go build -o gitlab-storage-cleaner cmd/gitlab-storage-cleaner/main.go

#############################
#         STAGE RUN         #
#############################
FROM gcr.io/distroless/static-debian12:nonroot

LABEL org.opencontainers.image.authors="kilianpaquier"
LABEL org.opencontainers.image.vendor="kilianpaquier"

LABEL org.opencontainers.image.title="gitlab-storage-cleaner"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.url="github.com/kilianpaquier/gitlab-storage-cleaner"
LABEL org.opencontainers.image.source="github.com/kilianpaquier/gitlab-storage-cleaner"
LABEL org.opencontainers.image.documentation="github.com/kilianpaquier/gitlab-storage-cleaner"

WORKDIR /app

COPY --from=build \
    /app/gitlab-storage-cleaner \
    ./

EXPOSE 3000

ENTRYPOINT [ "/app/gitlab-storage-cleaner" ]