# Code generated by craft; DO NOT EDIT.

.PHONY: generate
generate:
	@cli-craft generate $(ARGS)

.PHONY: clean
clean:
	@go clean
	@git clean -Xf ./*

.PHONY: venv
venv:
	@python3 -m venv venv
	@. ./venv/bin/activate

.PHONY: requirements
requirements:
	@pip install -r requirements.txt

.PHONY: cli-cleaner
local-%:
	@python3 $*

build-docker:
	@docker build -t gitlab-storage-cleaner .
