stages:
  - cleanup

.storage-cleanup:
  stage: analysis
  image:
    name: ghcr.io/kilianpaquier/gitlab-storage-cleaner
    entrypoint: [""]
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: manual
  variables:
    GITLAB_TOKEN: <your_gitlab_access_token>
    PATHS: ^$CI_PROJECT_NAMESPACE\/.*$ # regexp matching
    THRESHOLD_DURATION: 168h
  script:
    - /app/cli-storage-cleaner clean \
      --token "$CICD_RW_TOKEN" \
      --server "$CI_SERVER_HOST" \
      --paths "$PATHS" \
      --threshold "$THRESHOLD_DURATION" \
      --dry-run

storage-cleanup:dry-run:
  extends: .storage-cleanup

storage-cleanup:
  extends: .storage-cleanup
  script:
    - /app/cli-storage-cleaner clean \
      --token "$CICD_RW_TOKEN" \
      --server "$CI_SERVER_HOST" \
      --paths "$PROJECTS" \
      --threshold "$THRESHOLD_DURATION"
