# Code generated by craft; DO NOT EDIT.

GCI_CONFIG_PATH := .golangci.yml

.PHONY: reports
reports:
	@mkdir -p reports/

.PHONY: lint
lint: reports
	@golangci-lint run -c ${GCI_CONFIG_PATH} --timeout 240s --fast --sort-results \
		--out-format checkstyle:reports/go-ci-lint.checkstyle.xml,colored-line-number $(ARGS) || \
		echo "golangci-lint failed, running 'make lint-fix' may fix some issues"

.PHONY: lint-fix
lint-fix: reports
	@ARGS="--fix" make -s lint

.PHONY: test
test:
	@go test ./... -count 1

.PHONY: test-race
test-race:
	@go test ./... -race

.PHONY: test-cover
test-cover: reports
	@go test ./... -coverpkg="./..." -covermode="count" -coverprofile="reports/go-coverage.native.out"

.PHONY: buildall
buildall: build-gitlab-storage-cleaner

.PHONY: gitlab-storage-cleaner
build-%:
	@CGO_ENABLED=0 go build -o $* cmd/$*/main.go

.PHONY: gitlab-storage-cleaner
local-%:
	@go run cmd/$*/main.go

build-docker:
	@docker build -t gitlab-storage-cleaner .